ALTER TABLE orders
ADD COLUMN IF NOT EXISTS carrier VARCHAR(255);

ALTER TABLE orders
ADD COLUMN IF NOT EXISTS tracking_number VARCHAR(255);

ALTER TABLE orders
ADD COLUMN IF NOT EXISTS shipped_at TIMESTAMP;
